import { Resource,VectorSearchResultDTO } from "@/lib/types";

const topRelative = 6;

export async function searchResources(query: string): Promise<Resource[]> {
  const result = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL_WITH_API}/search`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      text: query,
      topRelatives: topRelative
    }),
  });

  if (!result.ok) throw new Error(`Search failed (${result.status})`);

  const responseJson = await result.json();
  const dtos: VectorSearchResultDTO[] = responseJson.result;

  return dtos.map(dto => ({
    id: crypto.randomUUID(),
    title: dto.title,
    description: dto.content,
    url: dto.url,
    imageUrl: "",
    tags: [],
    likes: 0,
    date: new Date().toISOString(),
    comment: "",
    isLiked: false,
    isBookmarked: false,
    recommended: false,
    authorName: "Unknown",
    authorAvatar: "https://avatar.iran.liara.run/public/boy",
    linkClicks: 0,
    createdAt: new Date().toISOString(),
  }));
}




export async function handleGlobalSearch(): Promise<Resource[]> {
  return [
    {
      id: "ai-1",
      title: "Awesome React Libraries (AI Search)",
      description: "Curated list of trending React libraries and tools, generated by SuperPro AI global search.",
      url: "https://github.com/ai/react-libraries",
      imageUrl: "",
      tags: ["React", "AI", "Trending"],
      likes: 0,
      date: new Date().toISOString(),
      isLiked: false,
      isBookmarked: false,
      recommended: false,
      authorName: "SuperPro AI",
      authorAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=ai",
      linkClicks: 0,
      createdAt: new Date().toISOString(),
      comment: "This list was generated by SuperPro AI global search. Enjoy exploring the latest in React!",
      isAIGenerated: true
    }
  ];
}