name: CI/CD for .NET

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['**']

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  ci-check:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

  deploy:
    if: github.event_name == 'push'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./dev-share-api/dev-share-api.csproj `
            --configuration Release `
            --output ./publish `
            -p:EnvironmentName=Test

      - name: Deploy to Azure Web App - Test
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-share-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish