name: CI/CD for FastAPI Embedding Service

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

env:
  PYTHON_VERSION: "3.13.x"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python-embedding/requirements.txt

      - name: Zip application for deployment
        run: |
          cd python-embedding
          zip -r ../python-embedding.zip ./

      - name: Deploy to Azure Web App (Linux)
        uses: azure/webapps-deploy@v3
        with:
          app-name: python-AI-model   
          publish-profile: ${{ secrets.AZURE_FASTAPI_PUBLISH_PROFILE }} 
          package: python-embedding.zip